### ISSUE TITLE
How can this work?

### ISSUE THREAD

**Issue by ddidier** [GitbookIO/plugin-styles-sass#3]
First I'm no JS or Node expert. I followed the simple instructions on the README page but that wasn't working. After much debugging with my limited knowledge I came to the conclusion that cannot possibly work or I'm really missing something.

In `website.js` in `prepareStyles` at [line 52](https://github.com/GitbookIO/gitbook/blob/5c16aec096b7d711f5206f7b251f2d6fbee18618/lib/generators/website.js#L52) : `that.book.resolve(stylePath)` is resolving the style path against the source root and not the generated `_book` directory. So it's working for a static file which is already there but not for a generated one which will be in the `_book` directory.

The only workaround I see without touching gitbook is to generated the CSS in the source, ie:

```
// Temporary CSS file
var tmpfile = filename.replace(/(sass|scss)$/i, "css");

// Replace config
book.config.set('styles.'+type, tmpfile);

return renderSASS(
    book.resolve(filename),
    path.resolve(tmpfile)
);
```

**Comment by ddidier** [comment]
See f50305427be83c2a435fc0fae4cafaa54b527652 for my ugly temporary fix

**Comment by SamyPesse** [comment]
Sorry for the delay, it'll fix with latest GitBook version( https://github.com/GitbookIO/gitbook/commit/becd027563f361e7dc6824d18c58978b08aa6118)

**Comment by ddidier** [comment]
thanks, that's working now
